[package]
name = "md_client"
version.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
md_proto = { path = "../md_proto" }
md_wire = { path = "../md_wire" }
anyhow = "1.0.104"
prost = "0.14.4"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net"] }

[lints]
workspace = true
